services:
  # Kafka Service (KRaft mode - no Zookeeper)
  - type: web # Changed back to 'web' for testing on free tier
    name: kafka
    env: docker
    plan: free # Back to free tier for testing
    dockerfilePath: kafka/Dockerfile
    autoDeploy: false
    envVars:
      - key: KAFKA_CFG_NODE_ID
        value: "1"
      - key: KAFKA_CFG_PROCESS_ROLES
        value: "controller,broker"
      - key: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
        value: "1@localhost:9093"
      - key: KAFKA_CFG_LISTENERS
        value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      - key: KAFKA_CFG_ADVERTISED_LISTENERS
        value: "PLAINTEXT://kafka:9092" # This will be resolved internally by Render
      - key: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
        value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      - key: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
        value: "CONTROLLER"
      - key: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
        value: "PLAINTEXT"
      - key: ALLOW_PLAINTEXT_LISTENER
        value: "yes"
      - key: KAFKA_HEAP_OPTS
        value: "-Xmx200m -Xms100m" # Reduced for free tier
      - key: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
        value: "true"
      # Aggressive optimizations for free tier
      - key: KAFKA_CFG_LOG_RETENTION_HOURS
        value: "24" # Only 1 day retention
      - key: KAFKA_CFG_LOG_SEGMENT_BYTES
        value: "52428800" # 50MB segments (smaller)
      - key: KAFKA_CFG_LOG_RETENTION_BYTES
        value: "104857600" # 100MB max retention per topic
      - key: KAFKA_CFG_NUM_PARTITIONS
        value: "1" # Minimal partitions
      - key: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
        value: "1" # Single node deployment
