services:
  - type: web
    name: zookeeper
    env: docker
    plan: free
    dockerfilePath: zookeeper/Dockerfile
    autoDeploy: false

  - type: web
    name: kafka
    env: docker
    plan: free
    dockerfilePath: kafka/Dockerfile
    autoDeploy: false
    envVars:
      - key: KAFKA_CFG_KRAFT_MODE
        value: "false"
      - key: KAFKA_CFG_ZOOKEEPER_CONNECT
        value: zookeeper:2181
      - key: KAFKA_CFG_LISTENERS
        value: PLAINTEXT://:9092
      - key: KAFKA_CFG_ADVERTISED_LISTENERS
        value: PLAINTEXT://kafka:9092
      - key: ALLOW_PLAINTEXT_LISTENER
        value: "yes"

