services:
  # Kafka Service (KRaft mode - no Zookeeper)
  - type: private
    name: kafka
    env: docker
    plan: free
    dockerfilePath: Dockerfile.kafka
    autoDeploy: false
    envVars:
      - key: KAFKA_CFG_NODE_ID
        value: "1"
      - key: KAFKA_CFG_PROCESS_ROLES
        value: "controller,broker"
      - key: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
        value: "1@localhost:9093"
      - key: KAFKA_CFG_LISTENERS
        value: "PLAINTEXT://:9092,CONTROLLER://:9093"
      - key: KAFKA_CFG_ADVERTISED_LISTENERS
        value: "PLAINTEXT://kafka:9092"
      - key: ALLOW_PLAINTEXT_LISTENER
        value: "yes"
      - key: KAFKA_HEAP_OPTS
        value: "-Xmx256m -Xms128m"
