services:
  - type: private
    name: zookeeper
    env: docker
    plan: free
    autoDeploy: false
    dockerfilePath: zookeeper/Dockerfile

  - type: private
    name: kafka
    env: docker
    plan: free
    autoDeploy: false
    dockerfilePath: kafka/Dockerfile
